### ISSUE TITLE
Error! Bad return status for module build on kernel: 3.10.0-229.11.1.el7.x86_64

### ISSUE THREAD

**Issue by michaelkingbaa** [Grief/archer-t4u#1]
Hi,

I'm seeing an error while building the driver for the Archer-T4U. I've attached my make.log file.

Thanks,

Mike

[make_log.txt](https://github.com/Grief/archer-t4u/files/1229452/make_log.txt)

**Comment by Grief** [comment]
@michaelkingbaa You can find that README explicitly states that
>**The driver is supposed to be used only with Archer T4U V1 device and the latest (4.8.1-4.10) kernel only**

You can try [this driver](https://github.com/abperiasamy/rtl8812AU_8821AU_linux) for an older kernel if you don't want to upgrade it.
